PLATFORM_COLUMN_MAPS = {
    "facebook": {
        "Campaign Name": "campaign_name",
        "Amount Spent": "acquisition_cost",
        "Impressions": "impressions",
        "Clicks": "clicks",
        "Conversions": "conversions",
        "Reach": "reach",
        "Frequency": "frequency",
        "CPM": "cpm",
        "CTR": "ctr",
        "CPC": "cpc",
        "Date": "date",
        "Budget": "budget",
        "Revenue": "revenue",
        "Video Views": "video_views",
        "Engagement Score": "engagement_score",
        "Campaign Type": "campaign_type",
        "Target Audience": "target_audience",
        "Customer Segment": "customer_segment",
        "Language": "language",
        "Purchases": "purchases",
        "Leads": "leads",
    },
    "google": {
        "Campaign": "campaign_name",
        "Cost": "acquisition_cost",
        "Impressions": "impressions",
        "Clicks": "clicks",
        "Conversions": "conversions",
        "CTR": "ctr",
        "Avg. CPC": "cpc",
        "Date": "date",
        "Budget": "budget",
        "Revenue": "revenue",
        "Campaign Type": "campaign_type",
        "Target Audience": "target_audience",
        "Customer Segment": "customer_segment",
        "Language": "language",
        "Purchases": "purchases",
        "Leads": "leads",
    },
    "tiktok": {
        "Campaign name": "campaign_name",
        "Cost": "acquisition_cost",
        "Impressions": "impressions",
        "Clicks": "clicks",
        "Conversions": "conversions",
        "Video views": "video_views",
        "CTR": "ctr",
        "CPC": "cpc",
        "Date": "date",
        "Budget": "budget",
        "Revenue": "revenue",
        "Campaign Type": "campaign_type",
        "Target Audience": "target_audience",
        "Customer Segment": "customer_segment",
        "Language": "language",
    },
    "instagram": {
        "Campaign Name": "campaign_name",
        "Amount Spent": "acquisition_cost",
        "Impressions": "impressions",
        "Clicks": "clicks",
        "Conversions": "conversions",
        "Reach": "reach",
        "CTR": "ctr",
        "Date": "date",
        "Budget": "budget",
        "Revenue": "revenue",
        "Campaign Type": "campaign_type",
        "Target Audience": "target_audience",
        "Customer Segment": "customer_segment",
        "Language": "language",
    },
    "youtube": {
        "Campaign": "campaign_name",
        "Cost": "acquisition_cost",
        "Impressions": "impressions",
        "Views": "video_views",
        "Clicks": "clicks",
        "Conversions": "conversions",
        "CTR": "ctr",
        "Date": "date",
        "Budget": "budget",
        "Revenue": "revenue",
    },
    "twitter": {
        "Campaign Name": "campaign_name",
        "Spend": "acquisition_cost",
        "Impressions": "impressions",
        "Clicks": "clicks",
        "Conversions": "conversions",
        "CTR": "ctr",
        "Date": "date",
        "Budget": "budget",
        "Revenue": "revenue",
    },
    "pinterest": {
        "Campaign": "campaign_name",
        "Spend": "acquisition_cost",
        "Impressions": "impressions",
        "Clicks": "clicks",
        "Conversions": "conversions",
        "CTR": "ctr",
        "Date": "date",
        "Budget": "budget",
    },
    "whatsapp": {
        "Campaign Name": "campaign_name",
        "Cost": "acquisition_cost",
        "Impressions": "impressions",
        "Clicks": "clicks",
        "Conversions": "conversions",
        "Date": "date",
        "Budget": "budget",
    },
    "email": {
        "Campaign Name": "campaign_name",
        "Cost": "acquisition_cost",
        "Impressions": "impressions",
        "Clicks": "clicks",
        "Conversions": "conversions",
        "Open Rate": "ctr",
        "Date": "date",
        "Budget": "budget",
        "Revenue": "revenue",
    },
}

def map_columns(df, platform):
    platform_key = platform.lower()
    mapping = PLATFORM_COLUMN_MAPS.get(platform_key, {})
    df = df.rename(columns=mapping)
    return df